stages:
  - build

build:
  image: nixos/nix
  stage: build
  script:
    - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
    - nix-channel --update
    - nix-shell --run "cd $(pwd); make"
    - mv _out/*.pdf ./
    - mv _out/html ./
  artifacts:
    paths: [ "*.pdf", "html/*" ]
